        name:  aaaa

        on:
          workflow_dispatch:
  

        jobs:
          build:
           name: GITHUB
           runs-on: [self-hosted, windows]
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            



undefined