name: CHECK-TIMEOUT-2

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - '**/Dockerfile'
      - '**/sonar-project.properties'

jobs:
  build:
    name: GITHUB
    runs-on: ubuntu-latest
    timeout-minutes: 1200  # Extend timeout to 20 hours (20 * 60 minutes)
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

  ORCHESTRATION:
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 1200  # Extend timeout to 20 hours (20 * 60 minutes)
    permissions:
      issues: write
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: suriyakanth1
          issue-title: "Orchestration"
          issue-body: "run_id: ${{ github.run_id }}"
