name: Sample_Release

on:
  workflow_dispatch:

jobs:
  build:
    name: GITHUB
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Debug
        run: ls -la $GITHUB_WORKSPACE

  JMETER:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download JMeter and Run Test
        run: |
          sshpass -p ClearC0de20S4 ssh -o StrictHostKeyChecking=no root@158.220.107.63 << EOF
          cd $HOME/github_workspace  # Assuming this is the correct directory on the remote machine
          ls -la  # Debugging output to verify workspace contents
          $GITHUB_WORKSPACE/apache-jmeter-5.4.1/bin/jmeter.sh -n -t $GITHUB_WORKSPACE/test.jmx -l $GITHUB_WORKSPACE/results.jtl
          EOF

