        name: TEST 29

        on:
          workflow_dispatch:
  

        jobs:
          build:
           name: GITHUB
           runs-on: windows-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            


        #---------------- Docker
          DOCKERHUB:
           needs: [build]
           runs-on: windows-latest
           steps:
             - name: Checkout code
               uses: actions/checkout@v2
             - name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
             - name: Login to Docker Hub
               uses: docker/login-action@v2
               with:
                 username: test7
                 password: fgfsfhjftstffdzdsftgc
             - name: Build and push
               uses: docker/build-push-action@v5
               with:
                  push: true
                  tags: test7/dockerimagebuild:test
            

    #---------------- sonarqube
          SONARQUBE:
            needs: [DOCKERHUB]
            runs-on: windows-latest
            steps:
              - uses: actions/checkout@master
              - name: SonarQube Scan
                uses: sonarsource/sonarqube-scan-action@master
            env:
                SONAR_TOKEN: squ_8c5e7438e05474ebcb879b70892d439619fe4daa
                SONAR_HOST_URL: http://158.220.107.63:9000/

      #---------------- VM
          VIRTUAL_MACHINE:
            runs-on: windows-latest
            needs: [SONARQUBE]
            steps:
               - name: Checkout code
                 uses: actions/checkout@v3

               - name: Deploy to Linux Server
                 run: |
                     sshpass -p ABC@123 ssh -o StrictHostKeyChecking=no Test1@158.220.107.63 "docker pull test7/dockerimagebuild:test && docker run --rm -p 3000:3000 -d test7/dockerimagebuild:test"