        name: Test msg

        on:
          workflow_dispatch:
  

        jobs:
          build:
           name: GITHUB
           runs-on: macos-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            



undefined